domain_path: /home/aditya/Documents/ZUB/AES_SV/vitis_ws/aes_128_platform/export/aes_128_platform/sw/standalone_psu_cortexa53_0
app_src_dir: /opt/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
